name: Publish to NPM

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          ADBLOCK: true
      - name: Get commit message
        run: echo "::set-output name=message::$(git log --no-merges -1 --oneline)"
      - name: Build the app
        run: yarn build
      - name: Run the tests
        run: yarn coverage
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
